/*
 * Copyright 2019-2021, Haiku, Inc. All rights reserved.
 * Distributed under the terms of the MIT License.
 *
 * Authors:
 *      Adrien Destugues, pulkomandy@pulkomandy.tk
 */


#include <int.h>

#include <platform/openfirmware/openfirmware.h>

intptr_t gFirmwareTraps;

status_t
arch_int_init(kernel_args *args)
{
	gFirmwareTraps = 0;
	// Preserve openfirmware traps so we can call them
	asm volatile("rdpr %%tba, %0" : "=r" (gFirmwareTraps) :);

	dprintf("Old trap handler was at %lx\n", gFirmwareTraps);

	// Take over fault handling from openfirmware
	extern uint32 gTrapHandler;
	of_call_client_function("SUNW,set-trap-table", 1, 0, &gTrapHandler);
	return B_OK;
}


status_t
arch_int_init_post_vm(kernel_args *args)
{
	return B_OK;
}


status_t
arch_int_init_post_device_manager(struct kernel_args *args)
{
	return B_OK;
}


status_t
arch_int_init_io(kernel_args* args)
{
	return B_OK;
}


void
arch_int_enable_io_interrupt(int irq)
{
}


void
arch_int_disable_io_interrupt(int irq)
{
}


void
arch_int_assign_to_cpu(int32 irq, int32 cpu)
{
}


extern "C" void
sparc_trap(int32 trap)
{
}


// Each trap handler contains exactly 8 instructions, except "fast" handlers
// which are larger to allow inlining more code.
// The generic handler switches to system state (to avoid erasing user
// registers) and then calls sparc_trap with the trap number as a parameter.
#define USER_TRAP_HANDLER(x) \
	"rdpr %wstate, %g1\n" \
	"save\n" \
	"clr %o1\n" \
	"ba %xcc, sparc_trap\n" \
	"mov " x ", %o0\n" \
	"nop\n" \
	"nop\n" \
	"nop\n"

#define SYSTEM_TRAP_HANDLER(x)       \
	"set gFirmwareTraps, %g1     \n" \
	"ldx [%g1 + " x " * 16], %g1 \n" \
	"jmpl %g1 + " x " * 16, %g0  \n" \
	"nop\n" \
	"nop\n" \
	"nop\n" \
	"nop\n"


asm(
	".globl gTrapHandler\n"
	"gTrapHandler:\n"
	SYSTEM_TRAP_HANDLER("0x0")
	SYSTEM_TRAP_HANDLER("0x1")
	SYSTEM_TRAP_HANDLER("0x2")
	SYSTEM_TRAP_HANDLER("0x3")
	SYSTEM_TRAP_HANDLER("0x4")
	SYSTEM_TRAP_HANDLER("0x5")
	SYSTEM_TRAP_HANDLER("0x6")
	SYSTEM_TRAP_HANDLER("0x7")
	SYSTEM_TRAP_HANDLER("0x8")
	SYSTEM_TRAP_HANDLER("0x9") // Unused on UltraSparc I and II
	SYSTEM_TRAP_HANDLER("0xA")
	SYSTEM_TRAP_HANDLER("0xB")
	SYSTEM_TRAP_HANDLER("0xC")
	SYSTEM_TRAP_HANDLER("0xD")
	SYSTEM_TRAP_HANDLER("0xE")
	SYSTEM_TRAP_HANDLER("0xF")
	SYSTEM_TRAP_HANDLER("0x10")
	SYSTEM_TRAP_HANDLER("0x11")
	SYSTEM_TRAP_HANDLER("0x12")
	SYSTEM_TRAP_HANDLER("0x13")
	SYSTEM_TRAP_HANDLER("0x14")
	SYSTEM_TRAP_HANDLER("0x15")
	SYSTEM_TRAP_HANDLER("0x16")
	SYSTEM_TRAP_HANDLER("0x17")
	SYSTEM_TRAP_HANDLER("0x18")
	SYSTEM_TRAP_HANDLER("0x19")
	SYSTEM_TRAP_HANDLER("0x1A")
	SYSTEM_TRAP_HANDLER("0x1B")
	SYSTEM_TRAP_HANDLER("0x1C")
	SYSTEM_TRAP_HANDLER("0x1D")
	SYSTEM_TRAP_HANDLER("0x1E")
	SYSTEM_TRAP_HANDLER("0x1F")
	SYSTEM_TRAP_HANDLER("0x20")
	SYSTEM_TRAP_HANDLER("0x21")
	SYSTEM_TRAP_HANDLER("0x22")
	SYSTEM_TRAP_HANDLER("0x23")
	SYSTEM_TRAP_HANDLER("0x24")
	SYSTEM_TRAP_HANDLER("0x25")
	SYSTEM_TRAP_HANDLER("0x26")
	SYSTEM_TRAP_HANDLER("0x27")
	SYSTEM_TRAP_HANDLER("0x28")
	SYSTEM_TRAP_HANDLER("0x29")
	SYSTEM_TRAP_HANDLER("0x2A")
	SYSTEM_TRAP_HANDLER("0x2B")
	SYSTEM_TRAP_HANDLER("0x2C")
	SYSTEM_TRAP_HANDLER("0x2D")
	SYSTEM_TRAP_HANDLER("0x2E")
	SYSTEM_TRAP_HANDLER("0x2F")
	SYSTEM_TRAP_HANDLER("0x30")
	SYSTEM_TRAP_HANDLER("0x31") // Unused on UltraSparc I and II
	SYSTEM_TRAP_HANDLER("0x32")
	SYSTEM_TRAP_HANDLER("0x33")
	SYSTEM_TRAP_HANDLER("0x34")
	SYSTEM_TRAP_HANDLER("0x35")
	SYSTEM_TRAP_HANDLER("0x36")
	SYSTEM_TRAP_HANDLER("0x37")
	SYSTEM_TRAP_HANDLER("0x38")
	SYSTEM_TRAP_HANDLER("0x39")
	SYSTEM_TRAP_HANDLER("0x3A")
	SYSTEM_TRAP_HANDLER("0x3B")
	SYSTEM_TRAP_HANDLER("0x3C")
	SYSTEM_TRAP_HANDLER("0x3D")
	SYSTEM_TRAP_HANDLER("0x3E")
	SYSTEM_TRAP_HANDLER("0x3F")
	SYSTEM_TRAP_HANDLER("0x40")
	SYSTEM_TRAP_HANDLER("0x41")
	SYSTEM_TRAP_HANDLER("0x42")
	SYSTEM_TRAP_HANDLER("0x43")
	SYSTEM_TRAP_HANDLER("0x44")
	SYSTEM_TRAP_HANDLER("0x45")
	SYSTEM_TRAP_HANDLER("0x46")
	SYSTEM_TRAP_HANDLER("0x47")
	SYSTEM_TRAP_HANDLER("0x48")
	SYSTEM_TRAP_HANDLER("0x49")
	SYSTEM_TRAP_HANDLER("0x4A")
	SYSTEM_TRAP_HANDLER("0x4B")
	SYSTEM_TRAP_HANDLER("0x4C")
	SYSTEM_TRAP_HANDLER("0x4D")
	SYSTEM_TRAP_HANDLER("0x4E")
	SYSTEM_TRAP_HANDLER("0x4F")
	SYSTEM_TRAP_HANDLER("0x50")
	SYSTEM_TRAP_HANDLER("0x51")
	SYSTEM_TRAP_HANDLER("0x52")
	SYSTEM_TRAP_HANDLER("0x53")
	SYSTEM_TRAP_HANDLER("0x54")
	SYSTEM_TRAP_HANDLER("0x55")
	SYSTEM_TRAP_HANDLER("0x56")
	SYSTEM_TRAP_HANDLER("0x57")
	SYSTEM_TRAP_HANDLER("0x58")
	SYSTEM_TRAP_HANDLER("0x59")
	SYSTEM_TRAP_HANDLER("0x5A")
	SYSTEM_TRAP_HANDLER("0x5B")
	SYSTEM_TRAP_HANDLER("0x5C")
	SYSTEM_TRAP_HANDLER("0x5D")
	SYSTEM_TRAP_HANDLER("0x5E")
	SYSTEM_TRAP_HANDLER("0x5F")
	SYSTEM_TRAP_HANDLER("0x60")
	SYSTEM_TRAP_HANDLER("0x61")
	SYSTEM_TRAP_HANDLER("0x62")
	SYSTEM_TRAP_HANDLER("0x63")
	SYSTEM_TRAP_HANDLER("0x64") // Fast instruction MMU miss
	SYSTEM_TRAP_HANDLER("0x65") // ...
	SYSTEM_TRAP_HANDLER("0x66") // ...
	SYSTEM_TRAP_HANDLER("0x67") // ...
	SYSTEM_TRAP_HANDLER("0x68") // Fast data MMU miss
	SYSTEM_TRAP_HANDLER("0x69") // ...
	SYSTEM_TRAP_HANDLER("0x6A") // ...
	SYSTEM_TRAP_HANDLER("0x6B") // ...
	SYSTEM_TRAP_HANDLER("0x6C")
	SYSTEM_TRAP_HANDLER("0x6D")
	SYSTEM_TRAP_HANDLER("0x6E")
	SYSTEM_TRAP_HANDLER("0x6F")
	SYSTEM_TRAP_HANDLER("0x70")
	SYSTEM_TRAP_HANDLER("0x71")
	SYSTEM_TRAP_HANDLER("0x72")
	SYSTEM_TRAP_HANDLER("0x73")
	SYSTEM_TRAP_HANDLER("0x74")
	SYSTEM_TRAP_HANDLER("0x75")
	SYSTEM_TRAP_HANDLER("0x76")
	SYSTEM_TRAP_HANDLER("0x77")
	SYSTEM_TRAP_HANDLER("0x78")
	SYSTEM_TRAP_HANDLER("0x79")
	SYSTEM_TRAP_HANDLER("0x7A")
	SYSTEM_TRAP_HANDLER("0x7B")
	SYSTEM_TRAP_HANDLER("0x7C")
	SYSTEM_TRAP_HANDLER("0x7D")
	SYSTEM_TRAP_HANDLER("0x7E")
	SYSTEM_TRAP_HANDLER("0x7F")
	SYSTEM_TRAP_HANDLER("0x80")
	SYSTEM_TRAP_HANDLER("0x81")
	SYSTEM_TRAP_HANDLER("0x82")
	SYSTEM_TRAP_HANDLER("0x83")
	SYSTEM_TRAP_HANDLER("0x84")
	SYSTEM_TRAP_HANDLER("0x85")
	SYSTEM_TRAP_HANDLER("0x86")
	SYSTEM_TRAP_HANDLER("0x87")
	SYSTEM_TRAP_HANDLER("0x88")
	SYSTEM_TRAP_HANDLER("0x89")
	SYSTEM_TRAP_HANDLER("0x8A")
	SYSTEM_TRAP_HANDLER("0x8B")
	SYSTEM_TRAP_HANDLER("0x8C")
	SYSTEM_TRAP_HANDLER("0x8D")
	SYSTEM_TRAP_HANDLER("0x8E")
	SYSTEM_TRAP_HANDLER("0x8F")
	SYSTEM_TRAP_HANDLER("0x90")
	SYSTEM_TRAP_HANDLER("0x91")
	SYSTEM_TRAP_HANDLER("0x92")
	SYSTEM_TRAP_HANDLER("0x93")
	SYSTEM_TRAP_HANDLER("0x94")
	SYSTEM_TRAP_HANDLER("0x95")
	SYSTEM_TRAP_HANDLER("0x96")
	SYSTEM_TRAP_HANDLER("0x97")
	SYSTEM_TRAP_HANDLER("0x98")
	SYSTEM_TRAP_HANDLER("0x99")
	SYSTEM_TRAP_HANDLER("0x9A")
	SYSTEM_TRAP_HANDLER("0x9B")
	SYSTEM_TRAP_HANDLER("0x9C")
	SYSTEM_TRAP_HANDLER("0x9D")
	SYSTEM_TRAP_HANDLER("0x9E")
	SYSTEM_TRAP_HANDLER("0x9F")
	SYSTEM_TRAP_HANDLER("0xA0")
	SYSTEM_TRAP_HANDLER("0xA1")
	SYSTEM_TRAP_HANDLER("0xA2")
	SYSTEM_TRAP_HANDLER("0xA3")
	SYSTEM_TRAP_HANDLER("0xA4")
	SYSTEM_TRAP_HANDLER("0xA5")
	SYSTEM_TRAP_HANDLER("0xA6")
	SYSTEM_TRAP_HANDLER("0xA7")
	SYSTEM_TRAP_HANDLER("0xA8")
	SYSTEM_TRAP_HANDLER("0xA9")
	SYSTEM_TRAP_HANDLER("0xAA")
	SYSTEM_TRAP_HANDLER("0xAB")
	SYSTEM_TRAP_HANDLER("0xAC")
	SYSTEM_TRAP_HANDLER("0xAD")
	SYSTEM_TRAP_HANDLER("0xAE")
	SYSTEM_TRAP_HANDLER("0xAF")
	SYSTEM_TRAP_HANDLER("0xB0")
	SYSTEM_TRAP_HANDLER("0xB1")
	SYSTEM_TRAP_HANDLER("0xB2")
	SYSTEM_TRAP_HANDLER("0xB3")
	SYSTEM_TRAP_HANDLER("0xB4")
	SYSTEM_TRAP_HANDLER("0xB5")
	SYSTEM_TRAP_HANDLER("0xB6")
	SYSTEM_TRAP_HANDLER("0xB7")
	SYSTEM_TRAP_HANDLER("0xB8")
	SYSTEM_TRAP_HANDLER("0xB9")
	SYSTEM_TRAP_HANDLER("0xBA")
	SYSTEM_TRAP_HANDLER("0xBB")
	SYSTEM_TRAP_HANDLER("0xBC")
	SYSTEM_TRAP_HANDLER("0xBD")
	SYSTEM_TRAP_HANDLER("0xBE")
	SYSTEM_TRAP_HANDLER("0xBF")
	SYSTEM_TRAP_HANDLER("0xC0")
	SYSTEM_TRAP_HANDLER("0xC1")
	SYSTEM_TRAP_HANDLER("0xC2")
	SYSTEM_TRAP_HANDLER("0xC3")
	SYSTEM_TRAP_HANDLER("0xC4")
	SYSTEM_TRAP_HANDLER("0xC5")
	SYSTEM_TRAP_HANDLER("0xC6")
	SYSTEM_TRAP_HANDLER("0xC7")
	SYSTEM_TRAP_HANDLER("0xC8")
	SYSTEM_TRAP_HANDLER("0xC9")
	SYSTEM_TRAP_HANDLER("0xCA")
	SYSTEM_TRAP_HANDLER("0xCB")
	SYSTEM_TRAP_HANDLER("0xCC")
	SYSTEM_TRAP_HANDLER("0xCD")
	SYSTEM_TRAP_HANDLER("0xCE")
	SYSTEM_TRAP_HANDLER("0xCF")
	SYSTEM_TRAP_HANDLER("0xD0")
	SYSTEM_TRAP_HANDLER("0xD1")
	SYSTEM_TRAP_HANDLER("0xD2")
	SYSTEM_TRAP_HANDLER("0xD3")
	SYSTEM_TRAP_HANDLER("0xD4")
	SYSTEM_TRAP_HANDLER("0xD5")
	SYSTEM_TRAP_HANDLER("0xD6")
	SYSTEM_TRAP_HANDLER("0xD7")
	SYSTEM_TRAP_HANDLER("0xD8")
	SYSTEM_TRAP_HANDLER("0xD9")
	SYSTEM_TRAP_HANDLER("0xDA")
	SYSTEM_TRAP_HANDLER("0xDB")
	SYSTEM_TRAP_HANDLER("0xDC")
	SYSTEM_TRAP_HANDLER("0xDD")
	SYSTEM_TRAP_HANDLER("0xDE")
	SYSTEM_TRAP_HANDLER("0xDF")
	SYSTEM_TRAP_HANDLER("0xE0")
	SYSTEM_TRAP_HANDLER("0xE1")
	SYSTEM_TRAP_HANDLER("0xE2")
	SYSTEM_TRAP_HANDLER("0xE3")
	SYSTEM_TRAP_HANDLER("0xE4")
	SYSTEM_TRAP_HANDLER("0xE5")
	SYSTEM_TRAP_HANDLER("0xE6")
	SYSTEM_TRAP_HANDLER("0xE7")
	SYSTEM_TRAP_HANDLER("0xE8")
	SYSTEM_TRAP_HANDLER("0xE9")
	SYSTEM_TRAP_HANDLER("0xEA")
	SYSTEM_TRAP_HANDLER("0xEB")
	SYSTEM_TRAP_HANDLER("0xEC")
	SYSTEM_TRAP_HANDLER("0xED")
	SYSTEM_TRAP_HANDLER("0xEE")
	SYSTEM_TRAP_HANDLER("0xEF")
	SYSTEM_TRAP_HANDLER("0xF0")
	SYSTEM_TRAP_HANDLER("0xF1")
	SYSTEM_TRAP_HANDLER("0xF2")
	SYSTEM_TRAP_HANDLER("0xF3")
	SYSTEM_TRAP_HANDLER("0xF4")
	SYSTEM_TRAP_HANDLER("0xF5")
	SYSTEM_TRAP_HANDLER("0xF6")
	SYSTEM_TRAP_HANDLER("0xF7")
	SYSTEM_TRAP_HANDLER("0xF8")
	SYSTEM_TRAP_HANDLER("0xF9")
	SYSTEM_TRAP_HANDLER("0xFA")
	SYSTEM_TRAP_HANDLER("0xFB")
	SYSTEM_TRAP_HANDLER("0xFC")
	SYSTEM_TRAP_HANDLER("0xFD")
	SYSTEM_TRAP_HANDLER("0xFE")
	SYSTEM_TRAP_HANDLER("0xFF")
);
